import pygame
#Game settings
BLOCK_SIZE = 100
DISPLAYED_ROAD_SECTIONS = 10

WINDOW_WIDTH = BLOCK_SIZE * 9 + BLOCK_SIZE
WINDOW_HEIGHT = BLOCK_SIZE * DISPLAYED_ROAD_SECTIONS 

#Player settings
PLAYER_IMAGE = pygame.Surface((BLOCK_SIZE, BLOCK_SIZE)).fill((0, 0, 0))
MAX_TICKS_ON_ROAD_SECTION = 120

#Road settings